version: '3'

services:

  app:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    env_file: .env
    restart: always
    ports:
      - "8080:8080"
    links:
      - "couchdb:couchdb"
      - "odoo:odoo"
    depends_on:
      - odoo
      - couchdb
    volumes:
      - "./:/home/app/"

  couchdb:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.couchdb
    env_file: .env
    restart: always
    ports:
      - "5984:5984" # Expose port because it's used by the frontend
    volumes:
      - "couchdb-data:/opt/couchdb/data"

  database:
    image: "registry.gitlab.com/lgds/private-docker-images/postgres-lgds-anon:2021-04-28"
    env_file: .env
    restart: always
    volumes:
      - "odoo-pg-data:/var/lib/postgresql/data"
  odoo:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.odoo-lgds
    env_file: .env
    restart: always
    ports:
      - "8069:8069"
    links:
      - "database:database"
    depends_on:
      - database
    volumes:
      - "odoo-shared-data:/home/app/.local/share/Odoo"

volumes:
  odoo-shared-data:
  odoo-pg-data:
  couchdb-data:
